#!/bin/bash
cd
git clone https://github.com/slashtechno/push
cd push
sudo mv push /bin
sudo chmod +x /bin/push
sudo mkdir /etc/push
sudo chmod 777 /etc/push
touch /etc/push/site_directory.conf
touch /etc/push/server_IP.conf
touch /etc/push/git_repo.conf
touch /etc/push/git_username.conf
cd ..
sudo rm -r push
