#!/bin/bash
cd
git clone https://github.com/slashtechno/push-hugo
cd push-hugo
sudo mv push-hugo /bin
sudo chmod +x /bin/push-hugo
sudo mkdir /etc/push-hugo
sudo chmod 777 /etc/push-hugo
touch /etc/push-site/site_directory.conf
touch /etc/push-site/server_ip.conf
cd ..
sudo rm -r push-hugo
