#!/bin/python3

import os # needed to execute commands

# Function to set site directory
def set_site_dir():
    os.system("rm /etc/push-hugo/site_directory.conf")
    os.system("touch /etc/push-hugo/site_directory.conf")
    site_directory_file=open("/etc/push-hugo/site_directory.conf", "a")
    site_directory=input("\n\nWhat is you document root (Leave blank for default /var/www/html)\n")
    if not site_directory:
        site_directory="/var/www/html" 
    site_directory_file.write(site_directory)
    site_directory_file.close

def set_server_ip():
    os.system("rm /etc/push-hugo/server_IP.conf")
    os.system("touch /etc/push-hugo/server_IP.conf")
    server_IP_file=open("/etc/push-hugo/server_ip.conf", "a")
    server_IP=input("\n\nEnter user and ip adddress in this format:\nuser@server.ip\n")
    server_IP_file.write(server_IP)
    server_IP_file.close

while True:
    # Ask user what they want to do
    option = input("\n\nWhat would you like to do? \n1) Push Website\n2) Set site directory\n3) Set server IP and user\n4) Exit Program\n")
    option=int(option)
    if option == 1:
        server_IP_file = open(r"/etc/push-hugo/server_IP.conf") # open file that has server's IP adress
        server_IP = server_IP_file.read() # Read server IP
        if not server_IP:
            print("\nFirst setup server IP")
            set_server_ip()
        site_directory_file=open("/etc/push-hugo/site_directory.conf", "r") # open file that has the document root
        site_directory = site_directory_file.read() # read site directory    
        if not site_directory:
            print("\nFirst setup site directory")
        else:
            set_site_dir()
        os.system("ssh "+server_IP+" sudo rm -rf "+site_directory+"/*") # SSH into server and remove all files in website directory
        os.system("scp -r * " + server_IP + ":" + site_directory) # copy files to website directory on server
    elif option == 2:
        set_site_dir()
    elif option == 3:
        set_server_ip()
